### ISSUE TITLE
Thread error occurs in drawing object.

### ISSUE THREAD

**Issue by ZoroDerVonCodier** [SignalPop/TradingStudio#151]
Observed in 1.11.6.42

Stack trace:
at System.DateTime.op_Addition(DateTime d, TimeSpan t)
at DNN.net.fin.basecode.MarketTime.GetNextPeriod(DateTime dt, Int32 nPeriodsForward, Nullable`1 nSecondsInc, Boolean bEst)
at DNN.net.fin.basecode.MarketTime.GetTicksBetween(DateTime dt1, DateTime dt2, TimeSpan tsInc)
at DNN.net.app.tradingstudio.extension.drawing.DrawingObject.AdjustPoints(DateTime dt)
at DNN.net.app.tradingstudio.extension.drawing.DrawingObject.UpdateLocation(MouseData data)
at DNN.net.app.tradingstudio.extension.drawing.DrawingObjectCollection.UpdateLocations(MouseData data)
at DNN.net.app.tradingstudio.extension.drawing.DrawingControl.OnMouse(MouseData mouseData, UpdateData data)
at DNN.net.app.tradingstudio.extension.drawing.ExtensionComponent.OnMouse(MouseData mouseData, UpdateData data)
at DNN.net.app.tradingstudio.MgrExtensions.OnMouse(List`1 rgstrEnabled, MouseData mouseData)
at DNN.net.app.tradingstudio.FormChartDocument.simpleGraphingCtrl_OnUserMouseMove(Object sender, MouseEventArgs e)
at SimpleGraphing.SimpleGraphingControl.pbImage_MouseMove(Object sender, MouseEventArgs e)
at System.Windows.Forms.Control.OnMouseMove(MouseEventArgs e)
at System.Windows.Forms.Control.WmMouseMove(Message& m)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by ZoroDerVonCodier** [comment]
Fixed post 1.11.6.46
